//
// CurrentTimeSuccess.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CurrentTimeSuccess: Codable, JSONEncodable, Hashable {

    static let dataRule = StringRule(minLength: nil, maxLength: nil, pattern: "/hh:mm/")
    /** The response status code. */
    public var code: Int
    /** The response status description. */
    public var status: String
    /** Current time in the specified timezone. */
    public var data: String

    public init(code: Int, status: String, data: String) {
        self.code = code
        self.status = status
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case status
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(code, forKey: .code)
        try container.encode(status, forKey: .status)
        try container.encode(data, forKey: .data)
    }
}

