//
// Date.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DateClass: Codable, JSONEncodable, Hashable {

    public var readable: String?
    public var timestamp: String?
    public var gregorian: DateGregorian?
    public var hijri: DateHijri?

    public init(readable: String? = nil, timestamp: String? = nil, gregorian: DateGregorian? = nil, hijri: DateHijri? = nil) {
        self.readable = readable
        self.timestamp = timestamp
        self.gregorian = gregorian
        self.hijri = hijri
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case readable
        case timestamp
        case gregorian
        case hijri
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(readable, forKey: .readable)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
        try container.encodeIfPresent(gregorian, forKey: .gregorian)
        try container.encodeIfPresent(hijri, forKey: .hijri)
    }
}

