//
// DesignationAr.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DesignationAr: Codable, JSONEncodable, Hashable {

    public var abbreviated: String?
    public var expanded: String?

    public init(abbreviated: String? = nil, expanded: String? = nil) {
        self.abbreviated = abbreviated
        self.expanded = expanded
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case abbreviated
        case expanded
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(abbreviated, forKey: .abbreviated)
        try container.encodeIfPresent(expanded, forKey: .expanded)
    }
}

