//
// MethodParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MethodParams: Codable, JSONEncodable, Hashable {

    public var fajr: MethodParamsFajr?
    public var maghrib: MethodParamsMaghrib?
    public var isha: MethodParamsMaghrib?
    public var midnight: MethodParamsMaghrib?
    public var shafaq: MethodParamsMaghrib?

    public init(fajr: MethodParamsFajr? = nil, maghrib: MethodParamsMaghrib? = nil, isha: MethodParamsMaghrib? = nil, midnight: MethodParamsMaghrib? = nil, shafaq: MethodParamsMaghrib? = nil) {
        self.fajr = fajr
        self.maghrib = maghrib
        self.isha = isha
        self.midnight = midnight
        self.shafaq = shafaq
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fajr = "Fajr"
        case maghrib = "Maghrib"
        case isha = "Isha"
        case midnight = "Midnight"
        case shafaq = "Shafaq"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(fajr, forKey: .fajr)
        try container.encodeIfPresent(maghrib, forKey: .maghrib)
        try container.encodeIfPresent(isha, forKey: .isha)
        try container.encodeIfPresent(midnight, forKey: .midnight)
        try container.encodeIfPresent(shafaq, forKey: .shafaq)
    }
}

