//
// MethodsSuccessDataJAFARIParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MethodsSuccessDataJAFARIParams: Codable, JSONEncodable, Hashable {

    public var fajr: Double?
    public var maghrib: Double?
    public var isha: Double?
    public var midnight: String?

    public init(fajr: Double? = nil, maghrib: Double? = nil, isha: Double? = nil, midnight: String? = nil) {
        self.fajr = fajr
        self.maghrib = maghrib
        self.isha = isha
        self.midnight = midnight
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fajr = "Fajr"
        case maghrib = "Maghrib"
        case isha = "Isha"
        case midnight = "Midnight"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(fajr, forKey: .fajr)
        try container.encodeIfPresent(maghrib, forKey: .maghrib)
        try container.encodeIfPresent(isha, forKey: .isha)
        try container.encodeIfPresent(midnight, forKey: .midnight)
    }
}

