//
// MethodsSuccess.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MethodsSuccess: Codable, JSONEncodable, Hashable {

    /** The response status code. */
    public var code: Double
    /** The response status description. */
    public var status: String
    public var data: MethodsSuccessData

    public init(code: Double, status: String, data: MethodsSuccessData) {
        self.code = code
        self.status = status
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case status
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(code, forKey: .code)
        try container.encode(status, forKey: .status)
        try container.encode(data, forKey: .data)
    }
}

