//
// MethodsSuccessDataMWLParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MethodsSuccessDataMWLParams: Codable, JSONEncodable, Hashable {

    public var fajr: Double?
    public var isha: Double?

    public init(fajr: Double? = nil, isha: Double? = nil) {
        self.fajr = fajr
        self.isha = isha
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fajr = "Fajr"
        case isha = "Isha"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(fajr, forKey: .fajr)
        try container.encodeIfPresent(isha, forKey: .isha)
    }
}

