//
// MethodsSuccessDataMOONSIGHTINGParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MethodsSuccessDataMOONSIGHTINGParams: Codable, JSONEncodable, Hashable {

    public var shafaq: String?

    public init(shafaq: String? = nil) {
        self.shafaq = shafaq
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case shafaq
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(shafaq, forKey: .shafaq)
    }
}

