//
// MonthEn.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MonthEn: Codable, JSONEncodable, Hashable {

    public var number: Int?
    /** English name of the month  */
    public var en: String?

    public init(number: Int? = nil, en: String? = nil) {
        self.number = number
        self.en = en
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case number
        case en
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(number, forKey: .number)
        try container.encodeIfPresent(en, forKey: .en)
    }
}

