//
// Offset.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Offset: Codable, JSONEncodable, Hashable {

    public var imsak: OffsetImsak?
    public var fajr: OffsetFajr?
    public var sunrise: OffsetImsak?
    public var dhuhr: OffsetDhuhr?
    public var asr: OffsetAsr?
    public var maghrib: OffsetMaghrib?
    public var sunset: OffsetSunset?
    public var isha: OffsetIsha?
    public var midnight: OffsetMidnight?

    public init(imsak: OffsetImsak? = nil, fajr: OffsetFajr? = nil, sunrise: OffsetImsak? = nil, dhuhr: OffsetDhuhr? = nil, asr: OffsetAsr? = nil, maghrib: OffsetMaghrib? = nil, sunset: OffsetSunset? = nil, isha: OffsetIsha? = nil, midnight: OffsetMidnight? = nil) {
        self.imsak = imsak
        self.fajr = fajr
        self.sunrise = sunrise
        self.dhuhr = dhuhr
        self.asr = asr
        self.maghrib = maghrib
        self.sunset = sunset
        self.isha = isha
        self.midnight = midnight
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case imsak = "Imsak"
        case fajr = "Fajr"
        case sunrise = "Sunrise"
        case dhuhr = "Dhuhr"
        case asr = "Asr"
        case maghrib = "Maghrib"
        case sunset = "Sunset"
        case isha = "Isha"
        case midnight = "Midnight"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(imsak, forKey: .imsak)
        try container.encodeIfPresent(fajr, forKey: .fajr)
        try container.encodeIfPresent(sunrise, forKey: .sunrise)
        try container.encodeIfPresent(dhuhr, forKey: .dhuhr)
        try container.encodeIfPresent(asr, forKey: .asr)
        try container.encodeIfPresent(maghrib, forKey: .maghrib)
        try container.encodeIfPresent(sunset, forKey: .sunset)
        try container.encodeIfPresent(isha, forKey: .isha)
        try container.encodeIfPresent(midnight, forKey: .midnight)
    }
}

