//
// ResultItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ResultItem: Codable, JSONEncodable, Hashable {

    public var timings: Timings?
    public var date: DateClass?
    public var meta: Meta?

    public init(timings: Timings? = nil, date: DateClass? = nil, meta: Meta? = nil) {
        self.timings = timings
        self.date = date
        self.meta = meta
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case timings
        case date
        case meta
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(timings, forKey: .timings)
        try container.encodeIfPresent(date, forKey: .date)
        try container.encodeIfPresent(meta, forKey: .meta)
    }
}

