//
// WeekdayEnAr.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WeekdayEnAr: Codable, JSONEncodable, Hashable {

    /** English name of weekday  */
    public var en: String?
    /** Arabic name of weekday  */
    public var ar: String?

    public init(en: String? = nil, ar: String? = nil) {
        self.en = en
        self.ar = ar
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case en
        case ar
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(en, forKey: .en)
        try container.encodeIfPresent(ar, forKey: .ar)
    }
}

