//
// WeekdayEn.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WeekdayEn: Codable, JSONEncodable, Hashable {

    /** English name of weekday  */
    public var en: String?

    public init(en: String? = nil) {
        self.en = en
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case en
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(en, forKey: .en)
    }
}

